# NUMPY PART_02


In [1]:
import numpy as np
empty = np.empty([2,3])
empty

array([[-7.66179765e-312,  3.94476225e-103,  7.66214295e-312],
       [ 7.66214295e-312,  5.43472210e-323,  6.91691904e-323]])

In [2]:
x= np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [3]:
# array of even numbers
even=np.arange(0,23,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [4]:
# array of odd numbers 
odd = np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [5]:
# difference of 5
diff =np.arange(0,23,5)
diff

array([ 0,  5, 10, 15, 20])

In [6]:
# Linear space 
lin = np.linspace(0 , 20 , num=10)          # linearly growth between the numbers  by the given number 
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [11]:
lin.dtype

dtype('float64')

#  **Assignment:** What is the difference b/w data types?

In [7]:
# Sorting elements
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
a= np.array([1,2,3,4,5])
b= np.array([6,7,8,9,0])

In [10]:
# concatenation these array
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

### concatenate 2D arrays

In [13]:
x = np.array([[1,2],[3,4]])
y=np.array([[5,6]])
print(x,y)

[[1 2]
 [3 4]] [[5 6]]


In [12]:
z = np.concatenate((x,y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
x.ndim

2

In [15]:
y.ndim

2

In [16]:
z.ndim

2

# 3 Dimensional Array

In [19]:
# creating 3d array 
array_example = np.array ([[[0,1,2,3],
                            [4,5,6,7]],

                           [[8,9,0,1],
                            [2,3,4,5]],
                             
                             [[5,6,7,8],
                              [4,5,6,7]] ])

array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[8, 9, 0, 1],
        [2, 3, 4, 5]],

       [[5, 6, 7, 8],
        [4, 5, 6, 7]]])

In [20]:
array_example.ndim

3

In [21]:
array_example.size

24

In [22]:
len(array_example)

3

In [23]:
array_example.dtype

dtype('int32')

In [24]:
array_example.shape

(3, 2, 4)

In [26]:
a = np.array([[[0,1,2,3]],
              [[4,5,6,7]],
              [[4,6,7,9]]
              ])
a

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[4, 6, 7, 9]]])

In [27]:
a.shape

(3, 1, 4)

In [28]:
# Reshape the array
a = a.reshape(6,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [4, 6],
       [7, 9]])

In [29]:
a.shape

(6, 2)

In [33]:
# create a 1D array 
a= np.array([0,1,2,3,4,5,6])
a.shape

(7,)

In [32]:
# convert that into 2D
b = a[np.newaxis, :]        # adding rows
b

array([[0, 1, 2, 3, 4, 5, 6]])

In [34]:
c= a[:, np.newaxis]         ## adding column
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Indexing and Slicing

In [35]:
a =  np.array([0,1,2,3,4,5,6,7,8])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
a[2]

2

In [37]:
a[2:5]

array([2, 3, 4])

In [38]:
a[-4:]

array([5, 6, 7, 8])

In [39]:
a[-4:-2]

array([5, 6])

In [40]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
b[2]

array([ 9, 10, 11, 12])

In [43]:
b[b<5]

array([1, 2, 3, 4])

In [44]:
b[b%2==0]  # filter even number

array([ 2,  4,  6,  8, 10, 12])

In [45]:
b[b%2==1]   # filter odd number

array([ 1,  3,  5,  7,  9, 11])

In [46]:
# Use two condition using and (&) operator
b[(b > 2) & (b < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# OR (|) operator
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])